/*
Generated by npm run actiontypes
Using ../scripts/actiontypes.ts
Payload interfaces are kept in sync with Actions & Inputs defined in manifest.yml
*/
import type { CommonEvent } from "./forge/events";
import type { RovoContext } from "./rovo/action";
export interface LogAssessmentPayload extends CommonEvent {
  assessment: string;
  context: RovoContext;
}
export interface FetchContentFromIssuePayload extends CommonEvent {
  issue: string;
  context: RovoContext;
}
